### ISSUE TITLE
Allowing negative score in semi-global alignment

### ISSUE THREAD

**Issue by mdcao** [jeffdaily/parasail-python#29] opened 2018-12-02 17:27 UTC
Hi there
Thanks you for making a great alignment tool. I have been using it extensively, mostly for semi-global alignment.

I recently found a few very rare cases that semi-global alignment returned incorrect alignment, which I think because it did not allow negative alignment score like global alignment. Let me illustrate with an example. Consider two sequences

```
s1=CAGAACAGGACCACGACACTC
s2=ACACAGAAAAGGAACCCGCACTCCATC
```

where their alignment is

```
---CAGAACAGG-ACCACGACACTC---
   ||||| ||| ||| || |||||
ACACAGAAAAGGAACC-CG-CACTCCATC
```

If we run the semi-global alignment with large penalty, such as match=1, mismatch=gap_opening=gap_extension=-5, the semi_global alignment

```
match=1
mismatch=-5
gap_opening=-5
gap_extension=-5
user_matrix = parasail.matrix_create('ACGT', match, mismatch)
sg_aln = parasail.sg_trace_scan_sat(s1, s2, -gap_opening, -gap_extension, user_matrix)
print(sg_aln.cigar.decode, sg_aln.score)

# ('26D1=20I', 1)
# query   --------------------------CAGAACAGGACCACGACACTC',
#                                   |
# subject ACACAGAAAAGGAACCCGCACTCCATC--------------------',
#
```

The global alignment returns more sensible alignment, albeit incorrect towards the ends because it does not trim the two ends of the subject

```
match=1
mismatch=-5
gap_opening=-5
gap_extension=-5
user_matrix = parasail.matrix_create('ACGT', match, mismatch)
sg_aln = parasail.nw_trace_scan_sat(s1, s2, -gap_opening, -gap_extension, user_matrix)
print(sg_aln.cigar.decode, sg_aln.score)
# ('3D5=1X3=1D3=1I2=1D2=1X1=2D2=', -32)
# query    ---CAGAACAGG-ACCACG-ACAC--TC
#             ||||| ||| ||| || || |  ||  
# subject  ACACAGAAAAGGAACC-CGCACTCCATC
```

IMHO, it makes sense for the local alignment to not allow negative alignment score as we want only the significant (local) alignment from trimming the ends of both query and subject. However, for semi-global alignment, just like global alignment, we want the best alignment of the whole query and hence we should allow negative alignment score. Of course, if we have _sensible parameters_, that issue should not be there, but it is not always possible to have the best parameters in hand.

I am wondering if you consider implement this scoreing to make semi-global consistent with global aligmnent? 

Thanks
Minh

**Comment by jeffdaily** [comment] 2018-12-02 18:15
I will need to try reproducing your inputs to verify what’s going on. Global should be consistent with semi-global since they both allow the score to become negative.

I wonder if the error is caused by the integer size being used not being wide enough to hold intermediate solutions.  In any case, I’ll try to reproduce when I find time. Thanks for the report.

On Dec 2, 2018, at 9:27 AM, Minh Duc Cao <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there
Thanks you for making a great alignment tool. I have been using it extensively, mostly for semi-global alignment.

I recently found a few very rare cases that semi-global alignment returned incorrect alignment, which I think because it did not allow negative alignment score like global alignment. Let me illustrate with an example. Consider two sequences

s1=CAGAACAGGACCACGACACTC
s2=ACACAGAAAAGGAACCCGCACTCCATC


where their alignment is

---CAGAACAGG-ACCACGACACTC---
   ||||| ||| ||| || |||||
ACACAGAAAAGGAACC-CG-CACTCCATC


If we run the semi-global alignment with large penalty, such as match=1, mismatch=gap_opening=gap_extension=-5, the semi_global alignment

match=1
mismatch=-5
gap_opening=-5
gap_extension=-5
user_matrix = parasail.matrix_create('ACGT', match, mismatch)
sg_aln = parasail.sg_trace_scan_sat(s1, s2, -gap_opening, -gap_extension, user_matrix)
print(sg_aln.cigar.decode, sg_aln.score)

# ('26D1=20I', 1)
# query   --------------------------CAGAACAGGACCACGACACTC',
#                                   |
# subject ACACAGAAAAGGAACCCGCACTCCATC--------------------',
#


The global alignment returns more sensible alignment, albeit incorrect towards the ends because it does not trim the two ends of the subject

match=1
mismatch=-5
gap_opening=-5
gap_extension=-5
user_matrix = parasail.matrix_create('ACGT', match, mismatch)
sg_aln = parasail.nw_trace_scan_sat(s1, s2, -gap_opening, -gap_extension, user_matrix)
print(sg_aln.cigar.decode, sg_aln.score)
# ('3D5=1X3=1D3=1I2=1D2=1X1=2D2=', -32)
# query    CAGAACAGG-ACCACG-ACAC--TC
#          ||||| ||| ||| || || |  ||
# subject  CAGAAAAGGAACC-CGCACTCCATC


IMHO, it makes sense for the local alignment to not allow negative alignment score as we want only the significant (local) alignment from trimming the ends of both query and subject. However, for semi-global alignment, just like global alignment, we want the best alignment of the whole query and hence we should allow negative alignment score. Of course, if we have sensible parameters, that issue should not be an issue, but it is not always possible to have the best parameters in hand.

I am wondering if you consider implement this scoreing to make semi-global consistent with global aligmnent?

**Comment by mdcao** [comment] 2019-01-11 14:41
Hi @jeffdaily , wonder if you had a chance to look at the issue?

**Comment by jeffdaily** [comment] 2019-01-11 15:57
I was able to reproduce your results given your inputs.  Now I need to understand if it is doing the right thing for global and semi-global.

Have you tried your inputs with a different alignment tool to verify whether parasail's results are consistent with other tools?

**Comment by jeffdaily** [comment] 2019-01-11 16:43
One difference between semi-global and global is the boundary conditions.  In semi-global, the left-most column and upper row (not shown) are always initialized to 0 so as not to penalize the beginning of sequences.  In global, the initial conditions are -gap_open - gap_extend*i, where i is the index of the sequence.

The other difference is in global, the score is always the last value in the table.  In semi-global, the score is the maximum of the last row and last column (in this case, it is the first row's last value "1").

Based on your last comment, the seqanpy might be computing the same semi-global score table but it is selecting a different final score (green) versus parasail (red).

![image](https://user-images.githubusercontent.com/904248/51046984-55231000-157c-11e9-895b-b94fb183c9f5.png)

I'm not sure what the criteria would be for seqanpy's "overlap" selecting not the max in both the last row and column.  Perhaps it is selecting the max value for the shorter of the two sequences?  Or perhaps it will always only take the max of the last row since it assumes the query (s1) will always be smaller than the target (s2)?  Do you have any insight on this?

**Comment by jeffdaily** [comment] 2019-01-11 18:23
What I'm after is knowing what the canonical version of semi-global should be.  I thought it was what I had provided.  I am aware of an established parasail user base that depends on the current parasail semi-global behavior.  That said, I am not opposed to yet one more implementation so long as I don't duplicate too much code.

Parasail doesn't have any notion of options that can tweak algorithm behavior.  There are three primary algorithms, parasail sw, sg, and nw.  Since what you are requesting is a slight tweak of sg, I'm wondering how best to indicate this to the code.  An explicit function argument?  Something like 

```C
 extern parasail_result_t* parasail_nw_trace_scan_sat(
         const char * const restrict s1, const int s1Len,
         const char * const restrict s2, const int s2Len,
         const int open, const int gap,
         const parasail_matrix_t* matrix,
         const int flags); /* <-- the new parameter */
```

But that would be a backwards-incompatible change and I would rather avoid that.

How would you feel about a setting that could be turned on/off such as a new function `parasail_set_flags(int flags)`?  It could be called more than once during program execution in case you wanted to switch back and forth with the behavior.

I'm struggling a bit whether to say semi-global is giving the wrong answer.  If you changed your match and mismatch values to 5 and -4 as in the DNAfull matrix, you will get the alignment you expect.

**Comment by mdcao** [comment] 2019-01-11 19:32
Just saw your earlier comment. I think  it is ideal to specified which ends allowing gap penalties, that is to select the best core on the last column or last row. The `seqan` (C++ version) gave the options (where one can specify how the penalty in the ends should be handled), the python wrapper in seqanpy only implements a few  of them.

**Comment by mdcao** [comment] 2019-01-11 19:42
And just to give you an idea of the practical problem I am trying to do with semi-global here. Suppose I have a sequence read and I want to know from which genome it comes from. So I want the alignment to have gap penalty-free at only the two ends of the read, not at the end of the reference.

Again, thank so much for the great tool.
Minh

**Comment by jeffdaily** [comment] 2019-01-11 19:50
Thank you for that PDF.  It clearly outlines 8 cases for semi-global alignment.  Indeed, this means there is a deficiency in the current parasail semi-global implementation.  Currently, parasail semi-global does not penalize gaps in both sequences and at both ends, all at the same time.  Though this seems to work okay for some cases, it does not guarantee to return the desired alignment.  And the PDF you shared indicates this is not a correct implementation of semi-global alignment to allow gaps in both sequences at the same ends simultaneously.

I think the use case will be as I suggested earlier, a function for setting flags to control semi-global behavior.  I don't see a need for flags to control global or local alignment behavior since global and local alignment seems to be very well defined.  So I will create a function for tailoring semi-global behavior only.  Ideally, this would be an extra argument to the semi-global functions.  However, I have so much infrastructure in the code that assumes all alignment routines have the same function signature.

Would you agree that a user would set these semi-global flags once and only once for their application, or can you see a use case where you might want to allow gaps in the query during a portion of your application but then change it to disallow gaps later on?

**Comment by mdcao** [comment] 2019-01-11 19:56
This is how seqan letting the user to choose the semi-global mode they want using  `AlignConfig` class: https://seqan.readthedocs.io/en/master/Tutorial/Algorithms/Alignment/PairwiseSequenceAlignment.html#overlap-alignments

As for your question, I think an user may want to back and ford as they may have different problems at different points.

Thanks
Minh

**Comment by jeffdaily** [comment] 2019-01-12 00:42
The seqan docs show that the alignment options are passed to the global alignment routine.  That is probably the correct design, but ... I don't have a lot of time to get this implemented nor do I want to change interfaces, etc.

I think I'll go with some functions to set the semi-global flags system-wide such that the flags can be updated as needed.  I'll start a new feature branch for this work.  I'm not making any promises w.r.t. how fast I can get this done.  I'm doing this work in off hours as a hobby now.

**Comment by mdcao** [comment] 2019-01-14 15:16
That is so wonderful. I personally like suggestion 2 (or 3) as it is systematic and easy to follow. The last suggestion can give more succinct naming but it involves global and local which could create more confusions.
Look forward to these functions with thanks.
Minh

**Comment by jeffdaily** [comment] 2019-01-18 23:34
I have started my implementation.  Of course it's more work than I anticipated, but it is still feasible.
Branch: https://github.com/jeffdaily/parasail/tree/feature/sg
I've only currently created empty implementations of the new semi-global routines.  I went with suggestion 3 for naming.

**Comment by jeffdaily** [comment] 2019-01-19 00:01
Here's a sample of new outputs using your original s1 (query) and s2 (database/target).
```
// do not penalize query begin

optimal_alignment_score: -32
Target:          1 ACACAGAAAAGGAACC-CGCACTCCATC      27
                      |||||*||| ||| || ||*|  ||
Query:           1 ---CAGAACAGG-ACCACG-ACAC--TC      21

// do not penalize query end

optimal_alignment_score: -32
Target:          1 ACACAGAAAAGGAACC-CGCACTCCATC      27
                      |||||*||| ||| || ||*|  ||
Query:           1 ---CAGAACAGG-ACCACG-ACAC--TC      21

// do not penalize query beginning or end

optimal_alignment_score: -32
Target:          1 ACACAGAAAAGGAACC-CGCACTCCATC      27
                      |||||*||| ||| || ||*|  ||
Query:           1 ---CAGAACAGG-ACCACG-ACAC--TC      21

// do not penalize database begin

optimal_alignment_score: -17
Target:          1 ACACAGAAAAGGAACC-CGCACTCCATC      27
                      |||||*||| ||| || ||*|  ||
Query:           1 ---CAGAACAGG-ACCACG-ACAC--TC      21

// do not penalize database end

optimal_alignment_score: -17
Target:          1 ACACAGAAAAGGAACC-CG-CACTCCATC      27
                      |||||*||| ||| || |||||
Query:           1 ---CAGAACAGG-ACCACGACACTC----      21

// do not penalize database beginning or end

optimal_alignment_score: -2
Target:          1 ACACAGAAAAGGAACC-CG-CACTCCATC      27
                      |||||*||| ||| || |||||
Query:           1 ---CAGAACAGG-ACCACGACACTC----      21

// do not penalize query beginning or database end

optimal_alignment_score: -2
Target:          1 -----------------ACACAGAAAAGGAACCCGCACTCCATC      27
                                    ||*|
Query:           1 CAGAACAGGACCACGACACTC-----------------------      21

// do not penalize query end or database begin

optimal_alignment_score: 1
Target:          1 ACACAGAAAAGGAACCCGCACTCCATC--------------------      27
                                             |
Query:           1 --------------------------CAGAACAGGACCACGACACTC      21
```

**Comment by jeffdaily** [comment] 2019-01-23 19:17
Would you please review the changes to the README.md?

https://github.com/jeffdaily/parasail/blob/feature/sg/README.md

I want to make sure it is clear now that there are many semi-global variations, and how to use them.

**Comment by mdcao** [comment] 2019-01-23 20:15
Look perfectly clear to me. Really comprehensive.

In bioinformatics, the term `semi-global alignment` might mean different things to different people. You may want to put a pointer to the PDF lecture we looked at before, so the readers will have a clear idea of what you mean by semi-global alignments and their variations.

Thank again, and look forward to testing those functions.
-M

**Comment by jeffdaily** [comment] 2019-01-24 07:19
I have merged the new functions into the develop branch.  I will work on a C library release as well as updating the python wrappers.

**Comment by jeffdaily** [comment] 2019-02-11 18:55
C library released today.  Updated python bindings will also release today.

**Closed by jeffdaily** 2019-02-11 18:55 UTC
